<?php
/* Smarty version 3.1.39, created on 2021-07-26 10:19:41
  from '/Users/razib/Documents/valet/business-suite/apps/twofactor/views/enable.tpl' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.39',
  'unifunc' => 'content_60fec47de0cb93_48600842',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '306af62a792c39bd9283d32a96017df52afef760' => 
    array (
      0 => '/Users/razib/Documents/valet/business-suite/apps/twofactor/views/enable.tpl',
      1 => 1627309179,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_60fec47de0cb93_48600842 (Smarty_Internal_Template $_smarty_tpl) {
?><div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3>Setup Instructions</h3>
                <p><strong>1.</strong> Install the Google Authenticator App on your mobile device</p>
                <p><strong>2.</strong> In Google Authenticator, tap "+", and then "Scan Barcode."</p>
                <p><strong>3.</strong> Use your phone's camera to scan this barcode.</p>
                <p><strong>4.</strong> Once you have scanned the barcode, enter the 6-digit verification code generated by the Authenticator app.</p>
                <hr>
                <p><strong>Apps for Google Authenticator</strong></p>
                <a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" target="_blank"><img src="<?php echo $_smarty_tpl->tpl_vars['app_url']->value;?>
apps/twofactor/views/img/appstore_apple.png" alt="iOS App Store" style="max-width:180px"></a>
                <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en" target="_blank"><img src="<?php echo $_smarty_tpl->tpl_vars['app_url']->value;?>
apps/twofactor/views/img/appstore_android.png"  alt="Android App Store" style="max-width:154px"></a>

                <hr>
                <img id="img_qrcode" src="<?php echo $_smarty_tpl->tpl_vars['qr_code']->value;?>
" alt="example qr code">
                <hr>

                <form role="form" name="accadd" method="post" action="<?php echo $_smarty_tpl->tpl_vars['_url']->value;?>
twofactor/setup/enable_verify/">
                    <div class="form-group">
                        <label for="otp">Verification Code:</label>
                        <input type="text" class="form-control" id="otp" name="otp" placeholder="6 digit code">
                    </div>




                    <button type="submit" class="btn btn-primary">Verify Code</button>
                </form>

            </div>
        </div>
    </div>

</div>
<?php }
}
